server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Serve files if they exist, otherwise serve index.html
    location / {
        try_files $uri /index.html;
    }

    # Serve static files like JS, CSS
    location /static/ {
        root /usr/share/nginx/html;
    }

    # Optional: catch all errors and serve index.html
    error_page 404 /index.html;
}
